title:              SW0000J's Blog
email:              sw0000j@gmail.com
description:        SW0000J
#description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            "/"
url:                "https://SW0000J.github.io"

# Social Profiles
twitter_username:   
github_username:    SW0000J
facebook_username:  
instagram_username: woo_buddy
linkedin_username:  Seung Woo Jeong

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


exclude:
  - about.html
  - contact.html
  - bin/
  - posts/
  - jekyll-theme-clean-blog.gemspec